dataset:
  train:
    dir_path: data/train
    batch_size: 512
    num_workers: 4
  val:
    dir_path: data/val
    batch_size: 512
    num_workers: 4
  test:
    dir_path: data/test
    batch_size: 512
    num_workers: 4

train:
  network:
    board_size: 19
    in_channels: 18
  learning_rate: 0.05
  run_test: false

pl_trainer: {}

defaults:
  - logger: wandb
